on: 
  push

name: CI

jobs:
  build_and_test:
    name: build (x86_64-pc-windows-msvc)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-vcpkg
      - uses: actions-rs/cargo@v1
        with:
          command: vcpkg
          args: build --target x86_64-pc-windows-msvc
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-msvc
