name: CI

on: [push]

env:
  RUST_PROFILE: minimal
  RUST_VERSION: stable
  VCPKG_DEFAULT_BINARY_CACHE: /home/runner/vcpkg-binary-cache
  XDG_CACHE_HOME: /home/runner/.xdg

jobs:
  build:
    name: Build (${{ matrix.triplet }})
    strategy:
      matrix:
        include: 
          - os: ubuntu-latest
            triplet: x86_64-unknown-linux-gnu
            artifact: chip-8-emu
          # - os: windows-latest
          #   triplet: x86_64-pc-windows-msvc
          #   artifact: chip-8-emu.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get vcpkg metadata
        uses: SebRollen/toml-action@v1.0.1
        id: vcpkg_metadata
        with:
          file: Cargo.toml
          field: package.metadata.vcpkg
      - name: Prepare vcpkg directories and cache keys
        run: |
          mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
          mkdir -p $XDG_CACHE_HOME
          echo "VCPKG_CACHE_KEY=$(echo ${{ steps.vcpkg_metadata.outputs.value }} | sha256sum | tr -d '\n *-')" >> $GITHUB_ENV
          ls -la /home/runner
      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
            ${{ env.XDG_CACHE_HOME }}/vcpkg/archives
            ~/.cache/vcpkg/archives
          key: ${{ runner.os }}-vcpkg-${{ env.VCPKG_CACHE_KEY }}
      - name: Install Rust tools
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: ${{ matrix.triplet }}
          profile: ${{ env.RUST_PROFILE }}
          override: true
      - name: Cargo install cargo-vcpkg
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-vcpkg
      - name: Cache Cargo Rust
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo vcpkg -v build
      - run: cargo build --release