name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build_windows: 
    name: build (x86_64-pc-windows-msvc)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - run: | 
          cargo install cargo-vcpkg
          cargo vcpkg build
      - run: cargo build --release